### PR TITLE
Paint clones using track constraint like

### PR DESCRIPTION
**Pull request by s-leger**
Hi, 
Great work, thank you !!

Improved paint clones using a track constraint like alignment using 2 axes. (main and up vectors) 

You can paint objects with main axis following stroke, target surface normal, or global scene axis. Secondary axis is aligned to stroke or normal, depending on the first one, so objects alignment is way more predictable.

Also evaluate ideal stroke spacing when picking sources objects.

Perfect to draw arrows over any surfaces or trees.

Feel free to try and merge whatever part you may find usefull or not.

### CODE REVIEW

**Comment by mifth** [comment]
Hello!

Wow, you did the greatest tool. You Improved it a lot. And your code even better than mine.
And you rewrote the math. That's great. As I'm not good in math at all.
But I will not be able to support the math as I don't know matrices. (((

Possibly we should put this new tool as a separete tool?

**Comment by s-leger** [comment]
Well, 
I'm not so good as math as you may think, i only take a close look at blender track constraint sources.
Basically this part build a matrix from target main and up vectors, and compute the difference between source object main and up vectors. I only get rotation ( cob.to_quaternion() ) part of it since this allow random pre-transformations of object (rotations scaling and even moving),
If you need the whole matrix (for eg tool like maya ones) you may want to remove this to_quaternion conversion and use the matrix like this : final.location = matrix * original.location

Ok to merge as it, as a separate tool.

I don't want to make a repo for this tool as you already are known for it, and this way more users are able to find it.

**Comment by mifth** [comment]
No problem. I'll merge it. And I'll try to support it as much as I can. If Blender developers change something in new versions of the Blender...

**Comment by mifth** [comment]
I have put the Paint Clones at 'paint_clones' folder https://github.com/mifth/mifthtools/commit/6f4aac2a060f044f8b57e31655def80dc5fda5f1

**Comment by mifth** [comment]
By the way, I did not implement some things into the tool:
https://github.com/mifth/mifthtools/issues/11
https://github.com/mifth/mifthtools/issues/1

- BVH Picking. It works much faster
- rotate an instance after creation. For example to rotate to30 degrees at X axis after creation.
selection_040 
selection_040

- Draw on screen. For example, drawing at the screen view where the 2d cursor is.

**Pull request merged**
